/*
	A problem details object can have the following members:

   o  "type" (string) - A URI reference [RFC3986] that identifies the
	  problem type.  This specification encourages that, when
	  dereferenced, it provide human-readable documentation for the
	  problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
	  this member is not present, its value is assumed to be
	  "about:blank".

   o  "title" (string) - A short, human-readable summary of the problem
	  type.  It SHOULD NOT change from occurrence to occurrence of the
	  problem, except for purposes of localization (e.g., using
	  proactive content negotiation; see [RFC7231], Section 3.4).

   o  "status" (number) - The HTTP status code ([RFC7231], Section 6)
	  generated by the origin server for this occurrence of the problem.

   o  "detail" (string) - A human-readable explanation specific to this
	  occurrence of the problem.

   o  "instance" (string) - A URI reference that identifies the specific
	  occurrence of the problem.  It may or may not yield further
	  information if dereferenced.
 */

export abstract class HttpError extends Error {
	readonly status: number = 500
	readonly type: string = "internal-server-error"
	readonly detail: string
	readonly title: string = "Internal Server Error"

	constructor(message: string, err?: Error) {
		super(`${message} ${err ? err.message : ""}`)
		if (err) this.stack = err?.stack
		this.detail = message
	}
}

export class AuthenticationError extends HttpError {
	readonly status = 401
	readonly title = "Authentication Error"
	readonly type = "https://www.notion.so/todo"
}

export class AuthorizationError extends HttpError {
	readonly status = 403
	readonly title = "Authorization Error"
	readonly type = "https://www.notion.so/todo"
}

export class DatabaseError extends HttpError {
	readonly title = "database-error"
	readonly type = "db-error"
	readonly status = 500
}

export class NotFoundError extends HttpError {
	readonly title = "Not Found Error"
	readonly type = "not-found"
	readonly status = 404
}

export class NetworkError extends HttpError {
	readonly title = "network-error"
	readonly type = "netword-error"
	readonly status = 400
}
